windows:
  - name: RBR_config
    layout: main-vertical
    panes:
      - commands:
        - clear
        - echo "Configurations Windows"
      - commands:
        - clear
        - cd /Users/christopherhough/.myconfigurations
        - clear
      - commands:
        - clear
        - cd /Users/christopherhough/Code/AboutChrisHough/MyPrivateData
        - clear
      - commands:
        - clear
        - cd /Users/christopherhough/Code/AboutChrisHough/MyPublicData
        - clear
      - commands:
        - clear
        - cd /Users/christopherhough/Code
        - clear
        - lsa
